packages:
  - package
  - website

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild

overrides:
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  webpack@>=5.49.0 <5.104.0: '>=5.104.0'
  webpack@>=5.49.0 <=5.104.0: '>=5.104.1'
