packages:
  - package
  - website
onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
overrides:
  basic-ftp@<=5.2.1: '>=5.2.2'
  basic-ftp@=5.2.0: '>=5.2.1'
  defu@<=6.1.4: '>=6.1.5'
  lodash-es@<=4.17.23: '>=4.18.0'
  lodash-es@>=4.0.0 <=4.17.23: '>=4.18.0'
  lodash@<=4.17.23: '>=4.18.0'
  lodash@>=4.0.0 <=4.17.23: '>=4.18.0'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  undici@<6.24.0: '>=6.24.0'
  undici@>=6.0.0 <6.24.0: '>=6.24.0'
